server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.ebay.backend.config.SnakeCaseNamingStrategy
  profiles:
    active: local
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

